Changes to OpenAPI2Frank generator
emilykok/WAF-openapi-adapter pull request #4
Opened 2024-10-09 09:16 UTC by MarcoNL1

This pull request includes several updates to the `Dockerfile`, `README.md`, Java source files, and HTML templates to improve functionality and maintainability. Key changes include Dockerfile optimizations, documentation enhancements, new endpoints for handling XSD files, and template refactoring.

### Dockerfile Improvements:
* Added non-root user creation and switched to it for better security.
* Cleaned up Maven repository after building the application to reduce image size. 

### Documentation Enhancements:
* Updated project name and added instructions for cloning and running the project locally.

### Java Code Enhancements:
* Added support for additional content types and new endpoints for handling XSD files.
* Introduced `XSD` option in the `Option` enum and refactored template handling.

### HTML Template Updates:
* Updated file input to accept multiple content types and added new form actions for XSD files.
* Refactored Handlebars templates to use helper functions for handling status codes and conditional forwards.

### Miscellaneous:
* Updated copyright year to 2024.

2024-10-14 13:46 UTC, evandongen commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
>          // Check if it's a JSON file
Kan blijkbaar ook yaml zijn?

2024-10-14 13:46 UTC, evandongen commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
> +        if (!file.getContentType().matches("application/(json|yaml|x-yaml|octet-stream|text/yaml|plain)")) {
Als ik het zo goed lees, gaat het laatste stukje niet goed, tussen haakjes match je het stuk na `application/`, maar tussen haakjes staat ook `text/`. Daarnaast vraag ik me af of je hier octet-stream en text/plain wel wilt meenemen? Die zijn nogal generiek.

2024-10-14 13:46 UTC, evandongen commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
> +            if (!file.getContentType().equals("application/json"))
Kan je hier ook MediaType.APPLICATION_JSON gebruiken?

2024-10-14 13:46 UTC, evandongen commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
>          // Check if it's a JSON file
Dit is weer hetzelfde stukje. Kan je de content type check in een aparte method kwijt? Dan wordt het iets als `if (isSupportedContentType(file.getContentType())` oid

2024-10-14 13:46 UTC, evandongen commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
> +        if (!file.getContentType().matches("application/(json|yaml|x-yaml|octet-stream|text/yaml|plain)")) {
Sterker nog, ik zie 3x dezelfde code ;-) Als ik de hele body van deze method selecteer en 'extract method' in intellij kies, stelt hij zelfs voor om de 'Option' als extra parameter toe te voegen. Daarmee dupliceer je die code niet meer.

2024-10-14 13:46 UTC, evandongen commented on src/main/resources/templates/receiverTemplate.hbs
> +                    deepSearch="false">
Klopt dit?

2024-10-14 13:46 UTC, evandongen commented on src/main/resources/templates/senderTemplate.hbs
>              <Exits>
Kan dit exits blok in een aparte include oid? Dit is volgens mij precies hetzelfde als hierboven in receivertemplate. Daarmee komt inlineStatusExit ook gelijk op een logische plek uit.

2024-10-14 13:46 UTC, evandongen commented on src/test/java/nl/wearefrank/openapifrankadapter/XmlGeneratorTest.java
> +//    @Test
kan de gecommente code weg?

2024-10-16 12:10 UTC, thomaspj10 requested changes

2024-10-16 12:10 UTC, thomaspj10 commented on src/main/resources/templates/receiverTemplate.hbs
> +                    {{#if forwards.failure}}<Forward name="failure" path="InvalidXml"/>{{/if}}
Ik denk dat de forwards hier versimpeled kunnen worden (hetzelfde geldt voor de sender). 

De [documentatie](https://frankdoc.frankframework.org/#/All/Json2XmlValidator) zegt dat `failure` gebruikt moet worden wanneer de input niet aan de XSD voldoet. Hij roept nu een niet bestaande pipe of exit genaamd `InvalidXml` aan. Het zou leuk zijn als hij automatisch een 400 BadRequest teruggeeft.

`illegalRoot` bestaat niet en `parserError` wordt alleen aangeroepen wanneer de XSD niet correct is (ik ga er van uit dat deze tool altijd correcte XSDs produceert). De `success` forward mag van mij ook weg, omdat je dan automatisch naar de volgende pipe gaat (er bestaat nu geen pipe met naam `Build_query`)

2024-10-16 12:10 UTC, thomaspj10 commented on src/main/resources/templates/senderTemplate.hbs
> +                    {{#if forwards.failure}}<Forward name="failure" path="InvalidXml"/>{{/if}}
Hier hetzelfde als mijn vorige comment.

2024-10-16 12:10 UTC, thomaspj10 commented on src/main/resources/templates/receiverTemplate.hbs
> +                        {{> statusExit code="200" path="Success" state="SUCCESS"}}
Er zijn ontzettend veel status codes die bij een API gebruikt kunnen worden. Ik mis hier bijvoorbeeld 404 Not Found, maar er zijn nog veel andere minder populaire status codes. Kan je een manier verzinnen hoe deze lijst generiek gemaakt kan worden, zodat het alle status codes kan ondersteunen?

2024-10-16 12:23 UTC, thomaspj10 commented on src/main/resources/templates/receiverTemplate.hbs
> +{{!-- Helper function to handle status codes --}}
Deze templates zijn wel heel erg cool en ik denk dat er best veel tijd bespaart kan worden met de juiste templates. Misschien leuk om eens te kijken naar de mogelijkheden om voor meer use-cases een template te bouwen en hoe dat dan in backstage geimplementeerd kan worden.

2024-10-21 11:28 UTC, MarcoNL1 commented on src/main/java/nl/wearefrank/openapifrankadapter/OpenapiFrankadapterApplication.java
>          // Check if it's a JSON file
> Kan blijkbaar ook yaml zijn?

In de oorspronkelijke code werd er al gecheckt of het json of yaml was, alleen werkte yaml niet helemaal. Ik ging er dus van uit dat yaml ook een optie moest zijn.

2025-01-16 13:34 UTC, thomaspj10 commented
Feedback is present in https://github.com/wearefrank/openapi-frank-generator/pull/7, closing this PR.

2025-01-16 13:34 UTC, closed without merging